### ISSUE TITLE
Tree structure with recursive grouping

### ISSUE THREAD

**Issue by m4urer** [ceolter/angular-grid#126]
Having the data ungrouped where the grouping field is the parentCode:
>
0: {code: "ISLA1", description: null, locationLevel: "ISLE", parentCode: "WAREHOUSE"}
1: {code: "ISLA1-S1", description: null, locationLevel: "SECTOR", parentCode: "ISLA1"}
2: {code: "ISLA1-S1-P1", description: null, locationLevel: "POSITION", parentCode: "ISLA1-S1"}
3: {code: "ISLA1-S1-P1-T1", description: null, locationLevel: "STORE", parentCode: "ISLA1-S1-P1"}
4: {code: "ISLA1-S1-P1-T2", description: null, locationLevel: "STORE", parentCode: "ISLA1-S1-P1"}
....

When I use **groupKeys: ['parentCode']** I get only 1rst level grouping. I wish it would be recursive like the file explorer example, but starting from ungrouped/raw data.
Is it possible with some current configuration I'm missing? or the data has to be pre-grouped for the tree structure to work?

Thanks!!

**Comment by ceolter** [comment]
for the default grouping, you need to break the code out, eg:
{code1: "ISLA1", code2: "S1", code3: "P1", description: null, locationLevel: "STORE", parentCode: "ISLA1-S1-P1"}
and then groupKeys: ['code1','code2','code3']

i'm not sure that is what you want though, as you are providing it with parent nodes. the grid expects you to only provide leaf nodes, and it works out the intermediary levels.

as this is a question rather than an issue, i'm closing!!! can you use the bulletin board going forward for questions? thanks :)
