### ISSUE TITLE
Using server side sorting doesn't seem to fire the modelUpdated event when clicking on the header.

### ISSUE THREAD

**Issue by craigsh** [ceolter/angular-grid#250]
It would be great to be able to detect the sort order being changed so I can tell the server to prepare the data in a new order.

**Comment by ceolter** [comment]
the modelUpdated is from the inMemoryRowModel . . . . . . which is not used when doing Virtual Paging (aka infinate scrolling).

are you using infinite scrolling?

why do you want this event, if you are already in control (via the datasource) of the model updates??

**Comment by craigsh** [comment]
For various reasons I have to store a large dataset in a user's session on the server and the user can request sorted by any of the columns. The act of clicking on the header to sort would then tell the server to perform a sort then reload the grid. At present the only way for me to detect this would be to compare the sortModel in the getRows function with the last sortModel and when this changes, perform the re-sort on the server.

Does that make sense?

**Comment by ceolter** [comment]
yes it does make sense, but i don't think 'on model updated' is what you want. that's intended to be called after rows are loaded, that's the model that's the model that's updated. think you confusing it with the sort model - that doesn't trigger the model updated (but can cause it because it causes a data reload, but that's to late in your case).

sounds to me like a server side problem? you should compare the sort model to the previous sort model.

**Comment by craigsh** [comment]
Thanks for the reply.


Yes, you’re right, and I’ve just implemented that :)
