### ISSUE TITLE
[FEAT] Keyboard shortcuts

### ISSUE THREAD

**Issue by amcdnl** [ceolter/angular-grid#3]
A few things:

- Having the ability to select columns using CTRL or CTRL + Shift would be great for multiple select.
- Using arrow keys to move up and down or maybe even left and right would be great.

**Comment by amcdnl** [comment]
If you implement tab indexes and make it more accessible some of these come for free btw.

**Comment by ceolter** [comment]
Tabbing through cells is now implemented when you are editing.

**Comment by ceolter** [comment]
cell navigation is now implemented. includes navigation (up, down, left,right), tabs, enter (for opening and closing groups, or for starting to edit) and space (selection),

**Comment by amcdnl** [comment]
@ceolter you know if you put the issue number it ties the commit to the ticket ;)

**Comment by ceolter** [comment]
yup, i checked this in before closing the issue, it was more like "i need keyboard navigation" and then when it was done "oh yea, i think there was an issue raised for that" . . . . . sorry!!

btw @amcdnl i still have your list from last week, havn't forgot about it, just lots for me to to right now, i'm particularly interested in getting the memory leaks due to not removing listeners out asap

**Comment by valerieferrer** [comment]
Could you please tell me if it is planned to have the excel like navigation with CTRL+SHIFT available natively in AG GRID? If so when can we expect to have it?
