### ISSUE TITLE
Add a wrapper around v_elements and set style.top on it

### ISSUE THREAD

**Issue by S-YOU** [ceolter/angular-grid#407]
This isn't specific to angular-grid, but all other virtual scroll implementations are same.

When user scroll, each rows got style.top is set to keep track of scroll position.

![2015-08-28 20 04 59](https://cloud.githubusercontent.com/assets/1001175/9544963/1e75bdfa-4dc0-11e5-9f19-e6c61c5ec492.png)

Which means, if you have 30 items in dom, you need to touch DOM 30 times.
If you put a wrapper around v_elements, and set top to it, you can set top on it, only once.

**Comment by ceolter** [comment]
not really true. if you scroll down 5 rows, you still have to remove 5 rows and insert 5 rows, regardless of whether you use a wrapper div or not. you are just changing what the parent is. so no performance gain really.

in addition, if you go with the wrapper approach, the order of the element becomes an issue. this introduces a small bit more complexity. i don't see a worthwhile performance gain to be had to be worth the extra complexity.

**Comment by S-YOU** [comment]
Its indeed depend on how you implement vdom, but if you just patch existings nodes, instead of replacing it, it can be done. I have a demo that render with only visible rows, with wrapper approach.

http://rawgit.com/S-YOU/doTA/master/examples/virtual-scroll/index.html

But, of course its depend on implementation, just few ideas from me.

**Comment by ceolter** [comment]
i only vdom each row individually. i tested inserting all the rows in one go, but i didn't observe a big enough performance increase.

**Comment by clintb** [comment]
Please go in this direction for virtual scrolling. Patching existing dom items rather than killing/creating as you scroll performs so much better. I like ag-grid; and I think this would be an incredible upgrade.

**Comment by ceolter** [comment]
```
Patching existing dom items rather than killing/creating as you scroll performs so much better
```
not true in my tests - i did an implementation on moving rows rather than creating new ones, only went faster in firefox. see my presentation on such:
https://www.youtube.com/watch?v=gNhPeLCBbE0

**Comment by clintb** [comment]
From what I can tell, uiGrid does something like this (similar to your
skeleton approach) and it performs okay in all the browsers while scrolling
(but with the white-out draw delay).

I like what S-YOU suggested here:


http://rawgit.com/S-YOU/doTA/master/examples/virtual-scroll/index.html


I think he really took it to the extreme in his demonstration (moving just
one containing div, rather than each visible row). And in all the browsers
I test in; S-YOU's grid scrolls and draws data the fastest (no matter how
quickly I scroll). It's just that it doesn't have the awesome features of
ag-grid. His grid and your grid need to make a baby :)

I really like ag-grid. I especially find useful the master/slave feature
with a project I'm working on. If you don't have plans to incorporate what
S-YOU has demonstrated; I may take a crack at it after I finish this
project during the summer (if I have time). If you still have code from the
'Recycle' experiment you mentioned in your presentation, could I trouble
you put that out on gitHub, or make it an option in the grid options
(something like gridOptions.recycleSkeleton = true)?

Thank you for the work you've done. It really is a nifty grid.

Take care,

Clint

**Comment by ceolter** [comment]
```
His grid and your grid need to make a baby :)
```
hahahahahahahahahahahah, dag nammit i actually laughed out loud when i read that!

i don't have the skeleton code, i did it in a branch, then delete the branch. didn't think someone might want to use it.

with regards s-you's grid, yes it looks excellent. however he is also virtualising the columns, so it's not a like-for-like test. i have a big client who has 100+ columns in his reports and i will be fixing that. my plan is to virtualise the columns also.

**Comment by clintb** [comment]
Glad I gave you a chuckle. I appreciate your work man.

Right now, I'm dealing with it getting sluggish randomly. I'm sure it's
something I'm doing wrong or it may be a hang up in angular.

I'll keep an eye out for your x / y visualization update.
