### ISSUE TITLE
Stylus/SASS/Less styles

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/angular-grid#52]
It would be great to have the `src` styles utilize a css preprocessor.

**Comment by ceolter** [comment]
are the styles that complicated that we need something like scss?

On 10 April 2015 at 23:13, Tanner Linsley <notifications@github.com> wrote:

> It would be great to have the src styles utilize a css preprocessor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/52>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
Not at all. I'm such a fan of lean styles. I'm just throwing out any optimizations that come to mind.

**Comment by davidgeary** [comment]
I've been thinking the same about implementing this for the CSS.

Firstly, it's not that the styles are particularly complicated, but providing/maintaining predefined themes will definitely be simplified with the use of a preprocessor since each would just become a set of variables setting the required colours, etc, rather than needing to duplicate each of the related rules.  This, in turn, means that the rules are only defined once, so updating them doesn't need each theme to be changed separately.

More significantly though, I think it would make it much easier for developers to integrate the grid into a project that uses SASS/LESS.  Currently, you must manually copy and edit the grid styles to match your project (a process that then has to be repeated whenever the grid's styles are changed).  With SASS/LESS, you don't care about the rules themselves - as long as all the significant values have been declared as variables, you will only need to update the variables to match.  Upgrading to a new version then just needs you to check what variables have been added/removed.

Of course, whichever one you go with, someone will want you to implement the other one.  But I think implementing both is overkill.  Personally, I've used both SASS and LESS, but prefer SASS, so will probably have a go at converting it anyway (though I'm no expert).  I'll be happy to provide a PR as a first attempt, if you're interested.

**Comment by ceolter** [comment]
I use SASS (scss) in work, haven't used LESS. So I can't compare them, but
given I use SASS, that would be my preference. My reason for holding back
is I'm trying to minimise the complexity of the project. Although I use
SASS and am comfortable with it, not everyone is / does, so bringing in
another layer to the stack make the project less maintainable by some -
especially those who have arrived at JS development from traditional
application development (vs those who have come from creating websites).

Re the comments on style reuse - currently the styles are split into core
(always used) and theme (selected by user). So css styles that are part of
the operation of the grid are in core, so the themes don't need to be aware
off and repeat the core styling (not sure this is styling really, it's more
the skeleton layout of the grid). Was this what your were referring to as
the reusable parts?

If interested in the pull request, think Tanner has his eyes on this one!!!
But sure!! However it will be easier in a week or two when I get everything
moved over to git. Maybe my concern over 'making it difficult for non-css
people' can be eased by making sure we heavily inlne-comment the scss files
and extend the documentation to cover this.

On 11 April 2015 at 17:29, David Geary <notifications@github.com> wrote:

> I've been thinking the same about implementing this for the CSS.
>
> Firstly, it's not that the styles are particularly complicated, but
> providing/maintaining predefined themes will definitely be simplified with
> the use of a preprocessor since each would just become a set of variables
> setting the required colours, etc, rather than needing to duplicate each of
> the related rules. This, in turn, means that the rules are only defined
> once, so updating them doesn't need each theme to be changed separately.
>
> More significantly though, I think it would make it much easier for
> developers to integrate the grid into a project that uses SASS/LESS.
> Currently, you must manually copy and edit the grid styles to match your
> project (a process that then has to be repeated whenever the grid's styles
> are changed). With SASS/LESS, you don't care about the rules themselves -
> as long as all the significant values have been declared as variables, you
> will only need to update the variables to match. Upgrading to a new version
> then just needs you to check what variables have been added/removed.
>
> Of course, whichever one you go with, someone will want you to implement
> the other one. But I think implementing both is overkill. Personally, I've
> used both SASS and LESS, but prefer SASS, so will probably have a go at
> converting it anyway (though I'm no expert). I'll be happy to provide a PR
> as a first attempt, if you're interested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/52#issuecomment-91876235>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by davidgeary** [comment]
I can appreciate your concerns about complexity.  I assumed you hadn't used SASS/LESS because you didn't want to introduce additional third-party dependencies, but I can understand the other implications for some people.  That said, using a pre-processor is almost a tacit best practice (and so many OS frameworks/components use one or the other anyway), so maybe it's no bad thing.  And you can still distribute the CSS files too.

Regarding style reuse, I was referring more generally, though I'm ambivalent about the split between 'core' and 'theme' styles; it's useful when you have to work with the CSS directly, so could be maintained, but is less relevant and more complex when working in SASS.

I think the way the themes are currently implemented should change anyway.  I'm not a fan of the practice of adding the theme name to a parent element of the grid since, for most projects, you'll only ever be using a single fixed theme.  The only advantages I can see it giving is making it easy to try out different themes by simply changing the parent's class (which you can do just as easily by changing the stylesheet name) or where you have multiple grids on a single page that need different styling.  OTOH, the disadvantage is that you increase the browser's processing of the CSS since every element's style requires a traversal up the DOM to see if a parent has the `.ag-fresh` (or whatever) class.

Anyway, I'm fine with letting @tannerlinsley take the lead if he's up for it (always happy to let someone else do work!)

**Comment by tannerlinsley** [comment]
I'd love to do some style optimization.  My plan of attack would be this:

1. I'll wait until we start using gulp to move it to a preprocessor.  The build process needs to change before we can go much further.
2. Rewrite all of the src styles using Stylus, as it tends to be pretty agnostic and easy to convert to other preprocessors. Since Sass and Less are more commonly used (for now), we can easily convert the source stylus files to those types on build.  The markup for any preprocessor is going to be so similar, I don't think anyone will have a problem contributing, as there are so few differences between the preprocessors anyway.  Easy use of the files, customization compatibility and the ability to contribute easily should remain the focus.

**Comment by ceolter** [comment]
@tannerlinsley  is your suggesting for Stylus because you think it will take over from Sass and Less?

**Comment by ceolter** [comment]
@davidgeary re different styles used concurrently - yes i have that requirement - in my current project we have many reports in the same platform, the reports can have different styles.

**Comment by tannerlinsley** [comment]
Proposed fix #72

**Comment by tannerlinsley** [comment]
Fixed by #72
