### ISSUE TITLE
default cellrender in firefox

### ISSUE THREAD

**Issue by civic9** [ceolter/angular-grid#9]
Hi,

In RowRenderer.prototype.putDataIntoCell 
eGridCell.innerText = value;

doesn't work properly on firefox (at least under linux, firefox 36.0.1).
Cells are empty.

eGridCell.innerHTML = value;
works for me.

**Comment by ceolter** [comment]
thanks civic9, will investigate

**Comment by ceolter** [comment]
reproduced in firefox & windows

**Comment by civic9** [comment]
SetFilter.prototype.insertRow has similar problem. 
valueElement.innerText = displayNameOfValue;

**Comment by ceolter** [comment]
Now uses innerHTML instead. Tested in Chrome and FF. Checked in (but not released to web host yet, so online demo will still reference older version, will push to web host tonight). Thanks for raising the bug. :)

**Comment by oliver-breuer** [comment]
Instead of innerHTML you could use textContent and, if not available (on IE<=8) innerText instead.

Replacing innerText with innerHTML is a big semantic change. Because now all users need to escape all values.

In my opinion, this is a very dangerous change because it will (and probably already did) lead to security issues. Many people won't know that they need to escape the values. And even if they now, they can easily forget to do this at some places. Depending on where the values originate, there will be an HTML injection issue.

In some cases innerHTML could be a choice if you need to style the content. But even then it's probably safer to use some framework like AngularJS to render the content or create DOM elements and use appendChild().

In my opinion textContent/innerText should be the (safe) default and innerHTML should only explicitly be switched on via the api.
